### ISSUE TITLE
Found database PouchDB

### ISSUE THREAD

**Issue by lil5** [gorgabal/EnvelopeBudget#12]
# Duplicate

A duplicate of existing work may have been found!

## Follows all goals
- [MIT] open source
- [x] runs without 3rd party systems
- [n/a] good and understandable UX
- [n/a] adheres to the [Envelope system](https://en.wikipedia.org/wiki/Envelope_system)
- [n/a] accounts
- [n/a] envelopes (payment categories)
- [n/a] goals per envelope

### Description

Using PouchDB will use Redux for data calculations and structure. (there for some goals set at _n/a_)
Because PouchDB is written in Javascript an iOS version can be written without Java to Swift rewrite.

#### [electron & web](https://www.npmjs.com/package/pouchdb)
> https://pouchdb.com/
> PouchDB is an in-browser database that allows applications to save data locally, so that users can enjoy all the features of an app even when they're offline. Plus, the data is synchronized between clients, so users can stay up-to-date wherever they go.
>
> PouchDB also runs in Node.js and can be used as a direct interface to CouchDB-compatible servers. The API works the same in every environment, so you can spend less time worrying about browser differences, and more time writing clean, consistent code.

#### [react native](https://www.npmjs.com/package/pouchdb-react-native)
> https://github.com/stockulus/pouchdb-react-native/blob/master/readme.md
> [...] the version of PouchDB that is designed for ReactNative. In particular, it ships with the **AsyncStorage** adapters as its default adapters.

> https://facebook.github.io/react-native/docs/asyncstorage.html
> On iOS, AsyncStorage is backed by native code that stores small values in a serialized dictionary and larger values in separate files. On Android, AsyncStorage will use either RocksDB or SQLite based on what is available.

### Discrepancies

I have never used PouchDB and so do not know if it will work as I intend: 
* Data available after restart of app and/ or device
* Syncs well with other PouchDB devices

**Comment by gorgabal** [comment]
Hey, 

Since pouchDB is targetted to be in browser, I doubt that it will work for us, since it should also be possible to create an front-end without webdevelopment things. SQLlite already got us covered.

Just because the mobile app is going to be web-dev style, that does not mean the core should do that as well. The core should be implementation neutral.

**Comment by lil5** [comment]
@gorgabal you might want to reread the **react native** header on Asyncstorage
