### ISSUE TITLE
backend might be redundant

### ISSUE THREAD

**Issue by gorgabal** [gorgabal/EnvelopeBudget#4]
EnvelopeBudget now uses a self hacked-together backend. 

However, I just discovered a tool called ledger. 
http://ledger-cli.org/

And actually found some tutorials on making it work with envelope budgetting:
https://frdmtoplay.com/envelope-budgeting-with-ledger/

It might be worthwhile to allow ledger to be used as backend in the future.

**Comment by gorgabal** [comment]
Anyway, I am not sure what I am supposed to do with this information. My initial problem has basically been solved by that tool, but I am sure that a lot of people would benefit from an easy GUI program for envelope Budgeting.

**Comment by lil5** [comment]
@gorgabal You could change the backend to support the `leger` file system

Use leger as a standard

**Comment by lil5** [comment]
@gorgabal You could change the backend to support the `leger` file system

**Comment by gorgabal** [comment]
@lil5 I cannot find the 'leger' file system. Could you provide an URL for it?

**Comment by gorgabal** [comment]
I was thinking about learning to use ledger, and then rewrite this project to use it as an backend. That will put this project to an halt for a while.

**Comment by gorgabal** [comment]
issue #5 addresses this problem.

**Comment by lil5** [comment]
https://www.sitepoint.com/using-c-and-c-code-in-an-android-app-with-the-ndk/
running C++ in a Java app on android won't be a problem (but may suffer stability and speed)

Or I can make a [RESTful API web service](https://api-platform.com/) (but will necessitate a server and internet access)

You'll still need most of the code written to keep data ordered 

Leger is just a data aggregation tool, from what I've read up on

I will try to give an edited puml of what i mean in a pull request by tomorrow

**Comment by gorgabal** [comment]
hm, that might be true. you know what, I am just going to write an interface class to make swapping of backend more easy-ish. 

Internet access as an requirement is an no-go. Android app is optional.

**Comment by lil5** [comment]
please un-close the issue

**Comment by gorgabal** [comment]
Why? it was just a quick mental draft of my thoughts, those has been resolved, so the issue should remain closed.
